name: Test Report

on:
  workflow_dispatch:

jobs:
  gen-test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v2
        
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()    # run this step even if previous step failed
        with:
          name: sample tests
          path: test-reports/latest/test-report.xml
          reporter: java-junit
          
